[window]
decorations = "full"
opacity = 0.8

  [window.dimensions]
  columns = 100
  lines = 35

[font]
size = 10

  [font.normal]
  family = "MesloLGS NF"

  [font.bold]
  family = "MesloLGS NF"
  style = "Bold"

  [font.italic]
  family = "MesloLGS NF"
  style = "Italic"

  [font.bold_italic]
  family = "MesloLGS NF"
  style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
background = "#141d2b"
foreground = "#a4b1cd"

[colors.cursor]
text = "#141d2b"
cursor = "#a4b1cd"

[colors.selection]
text = "#141d2b"
background = "#141d2b"

[colors.normal]
black   = "#181818"
red     = "#FF5454"
green   = "#9fef00"
yellow  = "#FFD700"
blue    = "#39C5FF"
magenta = "#B839FF"
cyan    = "#39FFB8"
white   = "#C0C0C0"

[colors.bright]
black   = "#282828"
red     = "#FF6E6E"
green   = "#9fef00"
yellow  = "#FFF86E"
blue    = "#70D7FF"
magenta = "#D670FF"
cyan    = "#70FFD7"
white   = "#FFFFFF"
